version: '3'

services:
  app:
    # command: sh -l -c "bundle && bundle exec puma -v -b tcp://0.0.0.0:3000"
    build:
      context: .
      dockerfile: .docker/Dockerfile.app
      args:
        - BUNDLE_WITHOUT=production
    volumes:
      - .:/app/samvera/hyrax-webapp:cached
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    depends_on:
      - db
      - solr
      - fcrepo
    environment:
      - FCREPO_HOST=fcrepo
      - FCREPO_PORT=8080
      - FCREPO_BASE_PATH=''
      - SOLR_URL=http://solr:8983/solr/hydra-development
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile.worker
      args:
        - BUNDLE_WITHOUT=production
    volumes:
      - .:/app/samvera/hyrax-webapp:cached
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - worker-public:/app/samvera/hyrax-webapp/public
      - worker-tmp:/app/samvera/hyrax-webapp/tmp
    depends_on:
      - redis
    environment:
      - FCREPO_HOST=fcrepo
      - FCREPO_PORT=8080
      - FCREPO_BASE_PATH=''
      - SOLR_URL=http://solr:8983/solr/hydra-development

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=commarch
      - POSTGRES_USER=commarch
      - POSTGRES_PASSWORD=commarch

  redis:
    image: redis:alpine

  solr:
    image: solr:6.5.1
    volumes:
      - ./solr/conf:/opt/solr/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hydra-development
      - /opt/solr/conf
    ports:
      - "8983:8983"

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    ports:
      - 8080:8080

volumes:
  hyrax-derivatives:
  hyrax-uploads:
  rails-public:
  rails-tmp:
  worker-public:
  worker-tmp: