# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr/hydra-development' %>
beta:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983' %>/solr/hydra-beta
test:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr/hydra-test' %>
production:
  url: <%= ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr/hydra-production' %>
